zuul:
  routes:
    bar:
      serviceId: foo
      path: /foo
      stripPrefix: true
    portchange:
      path: /hello
      stripPrefix: false
      url: http://localhost:80

foo:
  ribbon:
    listOfServers: localhost:9080

barx:
  ribbon:
    listOfServers: localhost:7080
